var img=['1.jpg','2.jpg','3.jpg'];

    $(function(){
        var i=0;
        $('#change').css('background','url('+img[i]+')');
        setInterval(function(){
            i++;if(i==img.length){
                i=0;
            }
            $('#change').fadeIn('slow',function(){
                $(this).css('background','url('+img[i]+')');
                $(this).fadeIn('slow');
            })
        },3500);

        //

        $('.a2').click(function(){
            $('.tab2').css('display','block');
            $('.tab1').css('display','none');
            $('.tab3').css('display','none');
            $('.tab4').css('display','none');
            $('.tab5').css('display','none');
            $('.tab6').css('display','none');
        });
        $('.a3').click(function(){
            $('.tab3').css('display','block');
            $('.tab4').css('display','none');
            $('.tab5').css('display','none');
            $('.tab6').css('display','none');
            $('.tab1').css('display','none');
            $('.tab2').css('display','none');
        });
        $('.a4').click(function(){
            $('.tab4').css('display','block');
            $('.tab5').css('display','none');
            $('.tab6').css('display','none');
            $('.tab1').css('display','none');
            $('.tab2').css('display','none');
            $('.tab3').css('display','none');
        });
        $('.a5').click(function(){
            $('.tab5').css('display','block');
            $('.tab6').css('display','none');
            $('.tab1').css('display','none');
            $('.tab2').css('display','none');
            $('.tab3').css('display','none');
            $('.tab4').css('display','none');
        });
        $('.a6').click(function(){
            $('.tab6').css('display','block');
            $('.tab1').css('display','none');
            $('.tab2').css('display','none');
            $('.tab3').css('display','none');
            $('.tab4').css('display','none');
            $('.tab5').css('display','none');
        });
        $('.a1').click(function(){
            $('.tab1').css('display','block');
            $('.tab2').css('display','none');
            $('.tab3').css('display','none');
            $('.tab4').css('display','none');
            $('.tab5').css('display','none');
            $('.tab6').css('display','none');
        });
    });